### PR TITLE
Bump sbt-mu-srcgen to 0.22.1

### PR DESCRIPTION
**Pull request by cb372**
Not sure why scala-steward didn't do this for us

### CODE REVIEW

**Review by BenFradet — APPROVED** [review]
yes, it's been unreliable across different projects lately

**Comment by cb372** [comment]
@scala-steward Stop slacking! 😄

**Comment by fthomas** [comment]
It seems @scala-steward has problems loading the build of this repo:
```sbt
[info] loading settings for project petstore from build.sbt ...
[error] Invalid `scmInfo` connection value: scm:git:https://scala-steward@github.com/scala-steward/petstore4s.git
```
I've no idea why this is happening. Do you guys have any clue?

**Comment by fthomas** [comment]
Seems to me that you need to update sbt-github, so that Scala Steward can work on this repo again: https://github.com/alejandrohdezma/sbt-github/pull/189

/cc @alejandrohdezma

**Comment by cb372** [comment]
Thanks for taking the time to look into this @fthomas

**Comment by alejandrohdezma** [comment]
I'm working right now in updating all 47 Degrees repositories for the next release of [47degrees/.github](https://github.com/47degrees/.github/), which includes an upgrade of the `sbt-github` plugin.

**Comment by fthomas** [comment]
:+1:

Btw, these are all repositories that Scala Steward currently can't update because of this problem:
```
47degrees/github4s
47degrees/petstore4s
47degrees/sbt-hood
47degrees/sbt-microsites
47degrees/memeid
47degrees/scalacheck-toolbox
higherkindness/skeuomorph
higherkindness/mu-scala
higherkindness/sbt-mu-srcgen
scala-exercises/exercises-fetch
scala-exercises/evaluator
scala-exercises/exercises-pureconfig
scala-exercises/scala-exercises-runtime
scala-exercises/exercises-monocle
scala-exercises/exercises-scalacheck
scala-exercises/exercises-circe
scala-exercises/sbt-exercise
scala-exercises/exercises-doobie
scala-exercises/exercises-fpinscala
scala-exercises/exercises-stdlib
scala-exercises/exercises-template
scala-exercises/exercises-shapeless
scala-exercises/exercises-cats
scala-exercises/exercises-scalatutorial
```

**Pull request merged**
